apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>ArgoCD Apache</title>
    </head>
    <body>
      <h1>🎉 Hello from ArgoCD + Apache!</h1>
    </body>
    </html>
